import Head from "next/head";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <main>
      <Head>
        <title>My Porfolio</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
    </main>
  );
}
